language: ruby
rvm:
  - 2.6.3

services:
  - postgresql

env:
  - POSTGRES_USER=travis POSTGRES_PASSWORD=password POSTGRES_HOST=localhost POSTGRES_DEVELOPMENT_DB=volunteer_matching_dev POSTGRES_TEST_DB=volunteer_matching_test POSTGRES_DB=volunteer_matching

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  
script:
  - bundle exec rspec
  - bundle exec rubocop -a